CREATE TABLE [dbo].[countries](
	[countryID] [int] IDENTITY(1,1) NOT NULL,
	[countryCode] [nvarchar](max) NULL,
	[countryName] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.countries] PRIMARY KEY CLUSTERED 
(
	[countryID] ASC
)



INSERT INTO [dbo].[countries] VALUES ('AF', 'Afghanistan');
INSERT INTO [dbo].[countries] VALUES ('AL', 'Albania');
INSERT INTO [dbo].[countries] VALUES ('DZ', 'Algeria');
INSERT INTO [dbo].[countries] VALUES ('DS', 'American Samoa');
INSERT INTO [dbo].[countries] VALUES ('AD', 'Andorra');
INSERT INTO [dbo].[countries] VALUES ('AO', 'Angola');
INSERT INTO [dbo].[countries] VALUES ('AI', 'Anguilla');
INSERT INTO [dbo].[countries] VALUES ('AQ', 'Antarctica');
INSERT INTO [dbo].[countries] VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO [dbo].[countries] VALUES ('AR', 'Argentina');
INSERT INTO [dbo].[countries] VALUES ('AM', 'Armenia');
INSERT INTO [dbo].[countries] VALUES ('AW', 'Aruba');
INSERT INTO [dbo].[countries] VALUES ('AU', 'Australia');
INSERT INTO [dbo].[countries] VALUES ('AT', 'Austria');
INSERT INTO [dbo].[countries] VALUES ('AZ', 'Azerbaijan');
INSERT INTO [dbo].[countries] VALUES ('BS', 'Bahamas');
INSERT INTO [dbo].[countries] VALUES ('BH', 'Bahrain');
INSERT INTO [dbo].[countries] VALUES ('BD', 'Bangladesh');
INSERT INTO [dbo].[countries] VALUES ('BB', 'Barbados');
INSERT INTO [dbo].[countries] VALUES ('BY', 'Belarus');
INSERT INTO [dbo].[countries] VALUES ('BE', 'Belgium');
INSERT INTO [dbo].[countries] VALUES ('BZ', 'Belize');
INSERT INTO [dbo].[countries] VALUES ('BJ', 'Benin');
INSERT INTO [dbo].[countries] VALUES ('BM', 'Bermuda');
INSERT INTO [dbo].[countries] VALUES ('BT', 'Bhutan');
INSERT INTO [dbo].[countries] VALUES ('BO', 'Bolivia');
INSERT INTO [dbo].[countries] VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO [dbo].[countries] VALUES ('BW', 'Botswana');
INSERT INTO [dbo].[countries] VALUES ('BV', 'Bouvet Island');
INSERT INTO [dbo].[countries] VALUES ('BR', 'Brazil');
INSERT INTO [dbo].[countries] VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO [dbo].[countries] VALUES ('BN', 'Brunei Darussalam');
INSERT INTO [dbo].[countries] VALUES ('BG', 'Bulgaria');
INSERT INTO [dbo].[countries] VALUES ('BF', 'Burkina Faso');
INSERT INTO [dbo].[countries] VALUES ('BI', 'Burundi');
INSERT INTO [dbo].[countries] VALUES ('KH', 'Cambodia');
INSERT INTO [dbo].[countries] VALUES ('CM', 'Cameroon');
INSERT INTO [dbo].[countries] VALUES ('CA', 'Canada');
INSERT INTO [dbo].[countries] VALUES ('CV', 'Cape Verde');
INSERT INTO [dbo].[countries] VALUES ('KY', 'Cayman Islands');
INSERT INTO [dbo].[countries] VALUES ('CF', 'Central African Republic');
INSERT INTO [dbo].[countries] VALUES ('TD', 'Chad');
INSERT INTO [dbo].[countries] VALUES ('CL', 'Chile');
INSERT INTO [dbo].[countries] VALUES ('CN', 'China');
INSERT INTO [dbo].[countries] VALUES ('CX', 'Christmas Island');
INSERT INTO [dbo].[countries] VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO [dbo].[countries] VALUES ('CO', 'Colombia');
INSERT INTO [dbo].[countries] VALUES ('KM', 'Comoros');
INSERT INTO [dbo].[countries] VALUES ('CG', 'Congo');
INSERT INTO [dbo].[countries] VALUES ('CK', 'Cook Islands');
INSERT INTO [dbo].[countries] VALUES ('CR', 'Costa Rica');
INSERT INTO [dbo].[countries] VALUES ('HR', 'Croatia (Hrvatska)');
INSERT INTO [dbo].[countries] VALUES ('CU', 'Cuba');
INSERT INTO [dbo].[countries] VALUES ('CY', 'Cyprus');
INSERT INTO [dbo].[countries] VALUES ('CZ', 'Czech Republic');
INSERT INTO [dbo].[countries] VALUES ('DK', 'Denmark');
INSERT INTO [dbo].[countries] VALUES ('DJ', 'Djibouti');
INSERT INTO [dbo].[countries] VALUES ('DM', 'Dominica');
INSERT INTO [dbo].[countries] VALUES ('DO', 'Dominican Republic');
INSERT INTO [dbo].[countries] VALUES ('TP', 'East Timor');
INSERT INTO [dbo].[countries] VALUES ('EC', 'Ecuador');
INSERT INTO [dbo].[countries] VALUES ('EG', 'Egypt');
INSERT INTO [dbo].[countries] VALUES ('SV', 'El Salvador');
INSERT INTO [dbo].[countries] VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO [dbo].[countries] VALUES ('ER', 'Eritrea');
INSERT INTO [dbo].[countries] VALUES ('EE', 'Estonia');
INSERT INTO [dbo].[countries] VALUES ('ET', 'Ethiopia');
INSERT INTO [dbo].[countries] VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO [dbo].[countries] VALUES ('FO', 'Faroe Islands');
INSERT INTO [dbo].[countries] VALUES ('FJ', 'Fiji');
INSERT INTO [dbo].[countries] VALUES ('FI', 'Finland');
INSERT INTO [dbo].[countries] VALUES ('FR', 'France');
INSERT INTO [dbo].[countries] VALUES ('FX', 'France, Metropolitan');
INSERT INTO [dbo].[countries] VALUES ('GF', 'French Guiana');
INSERT INTO [dbo].[countries] VALUES ('PF', 'French Polynesia');
INSERT INTO [dbo].[countries] VALUES ('TF', 'French Southern Territories');
INSERT INTO [dbo].[countries] VALUES ('GA', 'Gabon');
INSERT INTO [dbo].[countries] VALUES ('GM', 'Gambia');
INSERT INTO [dbo].[countries] VALUES ('GE', 'Georgia');
INSERT INTO [dbo].[countries] VALUES ('DE', 'Germany');
INSERT INTO [dbo].[countries] VALUES ('GH', 'Ghana');
INSERT INTO [dbo].[countries] VALUES ('GI', 'Gibraltar');
INSERT INTO [dbo].[countries] VALUES ('GK', 'Guernsey');
INSERT INTO [dbo].[countries] VALUES ('GR', 'Greece');
INSERT INTO [dbo].[countries] VALUES ('GL', 'Greenland');
INSERT INTO [dbo].[countries] VALUES ('GD', 'Grenada');
INSERT INTO [dbo].[countries] VALUES ('GP', 'Guadeloupe');
INSERT INTO [dbo].[countries] VALUES ('GU', 'Guam');
INSERT INTO [dbo].[countries] VALUES ('GT', 'Guatemala');
INSERT INTO [dbo].[countries] VALUES ('GN', 'Guinea');
INSERT INTO [dbo].[countries] VALUES ('GW', 'Guinea-Bissau');
INSERT INTO [dbo].[countries] VALUES ('GY', 'Guyana');
INSERT INTO [dbo].[countries] VALUES ('HT', 'Haiti');
INSERT INTO [dbo].[countries] VALUES ('HM', 'Heard and Mc Donald Islands');
INSERT INTO [dbo].[countries] VALUES ('HN', 'Honduras');
INSERT INTO [dbo].[countries] VALUES ('HK', 'Hong Kong');
INSERT INTO [dbo].[countries] VALUES ('HU', 'Hungary');
INSERT INTO [dbo].[countries] VALUES ('IS', 'Iceland');
INSERT INTO [dbo].[countries] VALUES ('IN', 'India');
INSERT INTO [dbo].[countries] VALUES ('IM', 'Isle of Man');
INSERT INTO [dbo].[countries] VALUES ('ID', 'Indonesia');
INSERT INTO [dbo].[countries] VALUES ('IR', 'Iran (Islamic Republic of)');
INSERT INTO [dbo].[countries] VALUES ('IQ', 'Iraq');
INSERT INTO [dbo].[countries] VALUES ('IE', 'Ireland');
INSERT INTO [dbo].[countries] VALUES ('IL', 'Israel');
INSERT INTO [dbo].[countries] VALUES ('IT', 'Italy');
INSERT INTO [dbo].[countries] VALUES ('CI', 'Ivory Coast');
INSERT INTO [dbo].[countries] VALUES ('JE', 'Jersey');
INSERT INTO [dbo].[countries] VALUES ('JM', 'Jamaica');
INSERT INTO [dbo].[countries] VALUES ('JP', 'Japan');
INSERT INTO [dbo].[countries] VALUES ('JO', 'Jordan');
INSERT INTO [dbo].[countries] VALUES ('KZ', 'Kazakhstan');
INSERT INTO [dbo].[countries] VALUES ('KE', 'Kenya');
INSERT INTO [dbo].[countries] VALUES ('KI', 'Kiribati');
INSERT INTO [dbo].[countries] VALUES ('KP', 'Korea, Democratic People''s Republic of');
INSERT INTO [dbo].[countries] VALUES ('KR', 'Korea, Republic of');
INSERT INTO [dbo].[countries] VALUES ('XK', 'Kosovo');
INSERT INTO [dbo].[countries] VALUES ('KW', 'Kuwait');
INSERT INTO [dbo].[countries] VALUES ('KG', 'Kyrgyzstan');
INSERT INTO [dbo].[countries] VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO [dbo].[countries] VALUES ('LV', 'Latvia');
INSERT INTO [dbo].[countries] VALUES ('LB', 'Lebanon');
INSERT INTO [dbo].[countries] VALUES ('LS', 'Lesotho');
INSERT INTO [dbo].[countries] VALUES ('LR', 'Liberia');
INSERT INTO [dbo].[countries] VALUES ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO [dbo].[countries] VALUES ('LI', 'Liechtenstein');
INSERT INTO [dbo].[countries] VALUES ('LT', 'Lithuania');
INSERT INTO [dbo].[countries] VALUES ('LU', 'Luxembourg');
INSERT INTO [dbo].[countries] VALUES ('MO', 'Macau');
INSERT INTO [dbo].[countries] VALUES ('MK', 'Macedonia');
INSERT INTO [dbo].[countries] VALUES ('MG', 'Madagascar');
INSERT INTO [dbo].[countries] VALUES ('MW', 'Malawi');
INSERT INTO [dbo].[countries] VALUES ('MY', 'Malaysia');
INSERT INTO [dbo].[countries] VALUES ('MV', 'Maldives');
INSERT INTO [dbo].[countries] VALUES ('ML', 'Mali');
INSERT INTO [dbo].[countries] VALUES ('MT', 'Malta');
INSERT INTO [dbo].[countries] VALUES ('MH', 'Marshall Islands');
INSERT INTO [dbo].[countries] VALUES ('MQ', 'Martinique');
INSERT INTO [dbo].[countries] VALUES ('MR', 'Mauritania');
INSERT INTO [dbo].[countries] VALUES ('MU', 'Mauritius');
INSERT INTO [dbo].[countries] VALUES ('TY', 'Mayotte');
INSERT INTO [dbo].[countries] VALUES ('MX', 'Mexico');
INSERT INTO [dbo].[countries] VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO [dbo].[countries] VALUES ('MD', 'Moldova, Republic of');
INSERT INTO [dbo].[countries] VALUES ('MC', 'Monaco');
INSERT INTO [dbo].[countries] VALUES ('MN', 'Mongolia');
INSERT INTO [dbo].[countries] VALUES ('ME', 'Montenegro');
INSERT INTO [dbo].[countries] VALUES ('MS', 'Montserrat');
INSERT INTO [dbo].[countries] VALUES ('MA', 'Morocco');
INSERT INTO [dbo].[countries] VALUES ('MZ', 'Mozambique');
INSERT INTO [dbo].[countries] VALUES ('MM', 'Myanmar');
INSERT INTO [dbo].[countries] VALUES ('NA', 'Namibia');
INSERT INTO [dbo].[countries] VALUES ('NR', 'Nauru');
INSERT INTO [dbo].[countries] VALUES ('NP', 'Nepal');
INSERT INTO [dbo].[countries] VALUES ('NL', 'Netherlands');
INSERT INTO [dbo].[countries] VALUES ('AN', 'Netherlands Antilles');
INSERT INTO [dbo].[countries] VALUES ('NC', 'New Caledonia');
INSERT INTO [dbo].[countries] VALUES ('NZ', 'New Zealand');
INSERT INTO [dbo].[countries] VALUES ('NI', 'Nicaragua');
INSERT INTO [dbo].[countries] VALUES ('NE', 'Niger');
INSERT INTO [dbo].[countries] VALUES ('NG', 'Nigeria');
INSERT INTO [dbo].[countries] VALUES ('NU', 'Niue');
INSERT INTO [dbo].[countries] VALUES ('NF', 'Norfolk Island');
INSERT INTO [dbo].[countries] VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO [dbo].[countries] VALUES ('NO', 'Norway');
INSERT INTO [dbo].[countries] VALUES ('OM', 'Oman');
INSERT INTO [dbo].[countries] VALUES ('PK', 'Pakistan');
INSERT INTO [dbo].[countries] VALUES ('PW', 'Palau');
INSERT INTO [dbo].[countries] VALUES ('PS', 'Palestine');
INSERT INTO [dbo].[countries] VALUES ('PA', 'Panama');
INSERT INTO [dbo].[countries] VALUES ('PG', 'Papua New Guinea');
INSERT INTO [dbo].[countries] VALUES ('PY', 'Paraguay');
INSERT INTO [dbo].[countries] VALUES ('PE', 'Peru');
INSERT INTO [dbo].[countries] VALUES ('PH', 'Philippines');
INSERT INTO [dbo].[countries] VALUES ('PN', 'Pitcairn');
INSERT INTO [dbo].[countries] VALUES ('PL', 'Poland');
INSERT INTO [dbo].[countries] VALUES ('PT', 'Portugal');
INSERT INTO [dbo].[countries] VALUES ('PR', 'Puerto Rico');
INSERT INTO [dbo].[countries] VALUES ('QA', 'Qatar');
INSERT INTO [dbo].[countries] VALUES ('RE', 'Reunion');
INSERT INTO [dbo].[countries] VALUES ('RO', 'Romania');
INSERT INTO [dbo].[countries] VALUES ('RU', 'Russian Federation');
INSERT INTO [dbo].[countries] VALUES ('RW', 'Rwanda');
INSERT INTO [dbo].[countries] VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO [dbo].[countries] VALUES ('LC', 'Saint Lucia');
INSERT INTO [dbo].[countries] VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO [dbo].[countries] VALUES ('WS', 'Samoa');
INSERT INTO [dbo].[countries] VALUES ('SM', 'San Marino');
INSERT INTO [dbo].[countries] VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO [dbo].[countries] VALUES ('SA', 'Saudi Arabia');
INSERT INTO [dbo].[countries] VALUES ('SN', 'Senegal');
INSERT INTO [dbo].[countries] VALUES ('RS', 'Serbia');
INSERT INTO [dbo].[countries] VALUES ('SC', 'Seychelles');
INSERT INTO [dbo].[countries] VALUES ('SL', 'Sierra Leone');
INSERT INTO [dbo].[countries] VALUES ('SG', 'Singapore');
INSERT INTO [dbo].[countries] VALUES ('SK', 'Slovakia');
INSERT INTO [dbo].[countries] VALUES ('SI', 'Slovenia');
INSERT INTO [dbo].[countries] VALUES ('SB', 'Solomon Islands');
INSERT INTO [dbo].[countries] VALUES ('SO', 'Somalia');
INSERT INTO [dbo].[countries] VALUES ('ZA', 'South Africa');
INSERT INTO [dbo].[countries] VALUES ('GS', 'South Georgia South Sandwich Islands');
INSERT INTO [dbo].[countries] VALUES ('SS', 'South Sudan');
INSERT INTO [dbo].[countries] VALUES ('ES', 'Spain');
INSERT INTO [dbo].[countries] VALUES ('LK', 'Sri Lanka');
INSERT INTO [dbo].[countries] VALUES ('SH', 'St. Helena');
INSERT INTO [dbo].[countries] VALUES ('PM', 'St. Pierre and Miquelon');
INSERT INTO [dbo].[countries] VALUES ('SD', 'Sudan');
INSERT INTO [dbo].[countries] VALUES ('SR', 'Suriname');
INSERT INTO [dbo].[countries] VALUES ('SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO [dbo].[countries] VALUES ('SZ', 'Swaziland');
INSERT INTO [dbo].[countries] VALUES ('SE', 'Sweden');
INSERT INTO [dbo].[countries] VALUES ('CH', 'Switzerland');
INSERT INTO [dbo].[countries] VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO [dbo].[countries] VALUES ('TW', 'Taiwan');
INSERT INTO [dbo].[countries] VALUES ('TJ', 'Tajikistan');
INSERT INTO [dbo].[countries] VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO [dbo].[countries] VALUES ('TH', 'Thailand');
INSERT INTO [dbo].[countries] VALUES ('TG', 'Togo');
INSERT INTO [dbo].[countries] VALUES ('TK', 'Tokelau');
INSERT INTO [dbo].[countries] VALUES ('TO', 'Tonga');
INSERT INTO [dbo].[countries] VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO [dbo].[countries] VALUES ('TN', 'Tunisia');
INSERT INTO [dbo].[countries] VALUES ('TR', 'Turkey');
INSERT INTO [dbo].[countries] VALUES ('TM', 'Turkmenistan');
INSERT INTO [dbo].[countries] VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO [dbo].[countries] VALUES ('TV', 'Tuvalu');
INSERT INTO [dbo].[countries] VALUES ('UG', 'Uganda');
INSERT INTO [dbo].[countries] VALUES ('UA', 'Ukraine');
INSERT INTO [dbo].[countries] VALUES ('AE', 'United Arab Emirates');
INSERT INTO [dbo].[countries] VALUES ('GB', 'United Kingdom');
INSERT INTO [dbo].[countries] VALUES ('US', 'United States');
INSERT INTO [dbo].[countries] VALUES ('UM', 'United States minor outlying islands');
INSERT INTO [dbo].[countries] VALUES ('UY', 'Uruguay');
INSERT INTO [dbo].[countries] VALUES ('UZ', 'Uzbekistan');
INSERT INTO [dbo].[countries] VALUES ('VU', 'Vanuatu');
INSERT INTO [dbo].[countries] VALUES ('VA', 'Vatican City State');
INSERT INTO [dbo].[countries] VALUES ('VE', 'Venezuela');
INSERT INTO [dbo].[countries] VALUES ('VN', 'Vietnam');
INSERT INTO [dbo].[countries] VALUES ('VG', 'Virgin Islands (British)');
INSERT INTO [dbo].[countries] VALUES ('VI', 'Virgin Islands (U.S.)');
INSERT INTO [dbo].[countries] VALUES ('WF', 'Wallis and Futuna Islands');
INSERT INTO [dbo].[countries] VALUES ('EH', 'Western Sahara');
INSERT INTO [dbo].[countries] VALUES ('YE', 'Yemen');
INSERT INTO [dbo].[countries] VALUES ('ZR', 'Zaire');
INSERT INTO [dbo].[countries] VALUES ('ZM', 'Zambia');
INSERT INTO [dbo].[countries] VALUES ('ZW', 'Zimbabwe');
